name: swifty_chat
description: >-
  A Flutter package to quickly get started building Chat UIs
  with different type of message kinds.
version: 2.0.0
homepage: https://github.com/EnesKaraosman/swifty_chat
repository: https://github.com/EnesKaraosman/swifty_chat

environment:
  sdk: ">=3.1.0 <4.0.0"
  flutter: ">=3.13.0"

dependencies:
  # https://pub.dev/packages/carousel_slider
  carousel_slider: ^5.1.1

  # https://pub.dev/packages/equatable
  equatable: ^2.0.7

  flutter:
    sdk: flutter

  # https://pub.dev/packages/flutter_animate
  flutter_animate: ^4.5.0

  # https://pub.dev/packages/flutter_html
  flutter_html: ^3.0.0

  # https://pub.dev/packages/jiffy
  jiffy: ^6.4.4

  # https://pub.dev/packages/styled_widget
  styled_widget: ^0.4.1

  # https://pub.dev/packages/url_launcher
  url_launcher: ^6.3.2

dev_dependencies:
  faker: ^2.2.0

  # https://pub.dev/packages/flutter_lints
  flutter_lints: ^6.0.0

  flutter_test:
    sdk: flutter

  swifty_chat_mocked_data:
    path: ./packages/swifty_chat_mocked_data

flutter:
  uses-material-design: true
